### ISSUE TITLE
sideEffects flag disrupts treeshaking

### ISSUE THREAD

**Issue by Cheprer** [char0n/ramda-adjunct#742] opened 2018-11-20 19:05 UTC
Webpack sideEffects doesn't compile properly in latest version of Webpack `4.25.1`.

Removing it fixes this issue.

**Comment by Cheprer** [comment] 2018-11-20 19:12
In case you want to keep it, you need it rewrite default config of webpack, which is not nice and probably would raise more issues.

In case you have old ramda-adjunct and you have this issue you can't migrate to newer version here is a fix for your webpack-config:
```javascript
const webpackConfig = {
  resolve: {
    ...
    mainFields: ['browser', 'main'], // ramda-adjunct does not work with 'module' field.
}
```

**Comment by char0n** [comment] 2018-11-20 20:40
https://github.com/stereobooster/package.json#sideeffects

**Comment by char0n** [comment] 2018-11-20 21:01
Let me reproduce it first on webpack@4.25.1. What are the indicators that the bundle didn't compile properly ? I'd like to find (understand) the original problem in the code before I'll remove the flag

**Comment by char0n** [comment] 2018-11-20 22:30
Haven't been able to reproduce yet. Here is the gist with POC: https://gist.github.com/char0n/ae120af01bf17065c171494545d76a39

I'm running following command to build the bundle `./node_modules/.bin/webpack  --config webpack.config.js --verbose`.

I'm not seeing anything unusal in RA functions executions.

**Comment by Cheprer** [comment] 2018-11-21 09:59
If I understand correctly the `sideEffects` flag does not compile the functions which are not exported. So as long as there is a function which is not exported properly it could be missing in a build. Unfortunately I've checked the pathNotEq file where I noticed the issue and everything seems ok. I can investigate more later on in upcoming days.

**Comment by petrjaros** [comment] 2018-11-24 11:16
Here is an example where `pathNotEq` always returns false: https://gist.github.com/petrjaros/9d489bcfd05a3ca1225e568ee77accd1.
The problem only occurs when `monet@0.8.10` is used. The latest version of `monet` doesn't cause problems and everything works as expected.
So the problem was probably not caused by `ramda-adjunct`

**Comment by char0n** [comment] 2018-11-25 09:18
@petrjaros thanks for additional research.

@Cheprer can you pls find time to confirm what @petrjaros sais about monet <-> ramda-adjunct combination. I remember we had this problem before with monet.

Still I'm going to investigate `sideEffects` and how it really works in more details and decide if we're going to remove that or not.

**Comment by char0n** [comment] 2018-11-25 10:17
> If I understand correctly the sideEffects flag does not compile the functions which are not exported. So as long as there is a function which is not exported properly it could be missing in a build. Unfortunately I've checked the pathNotEq file where I noticed the issue and everything seems ok. I can investigate more later on in upcoming days.

@Cheprer yes your understanding of this is correct. Unfortunately we don't have any effect-full modules in ramda-adjunct. Every module contains some evaluation and then the results of evaluations are exported. We have none module that contains side effects and is only imported to do some polyfilling or whatever.

There is also a nicer explanation from webpack documentation about this:
```
A "side effect" is defined as code that performs a special behavior when imported, other than exposing 
one or more exports. An example of this are polyfills, which affect the global scope and usually do not 
provide an export.
```

To add to that, I still haven't been able to confirm any webpack configuration that causes build to be non-functional.

@Cheprer I'm inclined to keep this option until we have some other confirmations of this causing problem or until somebody can some up with real POC that this `sideEffects` causes real problems. If you think it's problem in you codebase (which we still don't have prove for) there is a way to turn in off in your webpack configuration specifically for ramda-adjunct by `Rule` - https://webpack.js.org/configuration/module/#rule-sideeffects

**Comment by petrjaros** [comment] 2018-11-26 07:51
I did some additional research of the code generated by Webpack and I believe the problem is caused by `monet`. Especially the part where the library is rewriting Javascript core objects:
https://github.com/monet/monet.js/blob/develop/src/monet-pimp.js#L79.
The reason why it caused problems before and now it is OK is that they moved these functions changing Javascript core objects into optional `monet-pimp` file.

**Comment by char0n** [comment] 2018-11-27 08:05
@petrjaros, @Cheprer glad we've figured it out. Using newer versions of monet is highly recommended because of this implicit fiddling with system prototypes. Can we close this, as this doesn't seem to be the cause of problem anymore ?

**Closed** 2018-12-04 21:16 UTC
Labels: bug, investigate
